services:
  db:
    image: postgres:15-alpine
    container_name: ee-expenses-db
    restart: always
    environment:
      POSTGRES_USER: ee_user
      POSTGRES_PASSWORD: ee_password
      POSTGRES_DB: ee_expenses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
